sudo: required

language: node

services:
  - docker

branches:
  only:
  - master

before_script:
    - cp .env.travis .env

jobs:
  include:
    - stage: Build Image and Push in Docker hub
      script:
      - echo "aaaaa"
